version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pg_db_ipag

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=ipag
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      
    restart: always



volumes:
  postgres-data: